# Downloads the two typefaces the interface uses and rewrites the stylesheet to point
# at local copies. The app is offline-first inside a WebView, so nothing may resolve
# against fonts.googleapis.com at runtime.
#
# Run again only when the font list below changes; the output is committed.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'src/assets/fonts'
$cssOut = Join-Path $root 'src/assets/fonts.css'

New-Item -ItemType Directory -Force $outDir | Out-Null

$families = 'IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600'
$url = "https://fonts.googleapis.com/css2?family=$families&display=swap"

# A modern desktop UA is what makes Google serve woff2 rather than legacy formats.
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
$css = (Invoke-WebRequest -Uri $url -Headers @{ 'User-Agent' = $ua } -UseBasicParsing).Content

# Google returns a @font-face per unicode subset. Cyrillic, Greek and Vietnamese would
# be dead weight in the APK — unlike on the web, every bundled file ships whether or not
# a glyph from it is ever requested.
$keep = @('arabic', 'latin')
$blocks = [regex]::Matches($css, '/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{[^}]*\}')
$kept = @()
foreach ($b in $blocks) {
    if ($keep -contains $b.Groups[1].Value) { $kept += $b.Value }
}
if ($kept.Count -eq 0) { throw 'No matching font subsets found - has the Google Fonts CSS format changed?' }
$css = [string]::Join("`r`n", $kept)

Get-ChildItem $outDir -Filter '*.woff2' -ErrorAction SilentlyContinue | Remove-Item -Force

$matches = [regex]::Matches($css, 'url\((https://[^)]+\.woff2)\)')
$seen = @{}
$index = 0

foreach ($m in $matches) {
    $remote = $m.Groups[1].Value
    if ($seen.ContainsKey($remote)) { continue }
    $index++
    $name = "plex-$index.woff2"
    $seen[$remote] = $name
    Invoke-WebRequest -Uri $remote -Headers @{ 'User-Agent' = $ua } -OutFile (Join-Path $outDir $name) -UseBasicParsing
    Write-Host "saved $name"
}

foreach ($pair in $seen.GetEnumerator()) {
    $css = $css.Replace($pair.Key, "./fonts/$($pair.Value)")
}

$header = "/* Generated by scripts/fetch-fonts.ps1 - do not edit by hand. */`r`n"
Set-Content -Path $cssOut -Value ($header + $css) -Encoding UTF8
Write-Host "wrote $cssOut ($($seen.Count) files)"
